CORF_MGMT/Controllers/CookedfoodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CORF_MGMT.Controllers
{
    public class CookedfoodController : Controller
    {
        // GET: Cookedfood
        public ActionResult Cooked()
        {

            return View();
        }
        public ActionResult Add()
        {
            return View();
        }
    }
}

CORF_MGMT/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CORF_MGMT.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

    }
}

CORF_MGMT/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CORF_MGMT;
namespace CORF_MGMT.Controllers
{
    
    public class LoginController : Controller
    {
        ANKEntities entity = new ANKEntities();
        // GET: Login
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login1(user ue)
        {

            try
            {

                var data = (from users in entity.users
                            where users.Email_id.Contains(ue.Email_id)
                            select new
                            {
                                users.Email_id
                            }).SingleOrDefault();
                var data1 = (from users in entity.users
                             where users.Password.Contains(ue.Password)
                             select new
                             {
                                 users.Password
                             }).SingleOrDefault();

                string uname = Convert.ToString(data);
                string pass = Convert.ToString(data1);

                if (!string.IsNullOrEmpty(uname) && !string.IsNullOrEmpty(pass))
                {
                    return RedirectToAction("Index", "test");
                }
                else
                {
                    Response.Write("Invalid user");
                }
            }
            catch(Exception ex)
            {
                throw ex;
            }
            //var udetails = (from users in entity.users
            //                select new
            //                {
            //                    users.Email_id,
            //                    users.Password
            //                }).ToList();
            return View(ue);
        }
           
      
    }

}

CORF_MGMT/Controllers/StudyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;


namespace CORF_MGMT.Controllers
{
    public class StudyController : Controller
    {
        private ANKEntities an = new ANKEntities();
        // GET: Study
        public ActionResult Study()
        {
            var studies = an.studies.Include(s => s.sponsor);
            return View(studies.ToList());
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult create([Bind(Include = "Study_Id,Study_Name,Start_Date,End_Date,Study_Duration,Population_Type,No_Of_Visit,Sponsor_Id,Objective")] study study)
        {

            if (ModelState.IsValid)
            {
                an.studies.Add(study);
                an.SaveChanges();
                return RedirectToAction("Study");
            }

            ViewBag.Sponsor_Id = new SelectList(an.sponsors, "Sponsor_Id", "Sponsor_Name", study.Sponsor_Id);
            return View(study);
        }
    }
}

CORF_MGMT/Controllers/testController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CORF_MGMT.Controllers
{
    public class testController : Controller
    {
        // GET: test
        public ActionResult Index()
        {
            return View();
        }
    }
}

CORF_MGMT/Views/Cookedfood/Add.cshtml
@model CORF_MGMT.cookedfood

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add</title>
    <style>
        .btn {
            background-color:darkblue;
        }

        .btn {
            background-color:darkblue; 
            border: none;
            color: white;
            padding: 5px 10px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
        }
    </style>
    

</head>

<body>

    
        @*@Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>cookedfood</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Cf_Id, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Cf_Id, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Cf_Id, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Cf_Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Cf_Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Cf_Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }

            <div>
                @Html.ActionLink("Back to List", "Cooked")
            </div>*@
    <div>
        <h4 align="center">Add a Cooked Item</h4>
        <h4 align="center">Food Item Name       <span style="color:red">*</span>       <input type="text" name="fname" required /></h4>
        <h4 align="center">Total Cookedfood Items in gms     <span style="color:red">*</span> <input type="text" name="fname" required /></h4>

        <table width="100%" border="1">
            <tr>
                <th><span style="color:red">*</span>  RawMaterials&nbsp;</th>
                <th><span style="color:red">*</span>  Weight in gms&nbsp;</th>


            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>


            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>


            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>


            </tr>
        </table>
        <br />
        <div align="center">
            <input type="button" class="btn" value="ADD" onclick="location.href='@Url.Action("Add","Cookedfood")'" />

            <input type="button" class="btn" value="Cancel" onclick="location.href='@Url.Action("Cooked","CookedFood")'" />
        </div>



      

    </div>
    </body>
</html>

CORF_MGMT/Views/Cookedfood/Cooked.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>



</head>
<body>
  
    <div>
        <h1 align="center">List Of Cooked Items</h1>
        <center>
            <span><b>Keyword</b></span> <input type="text" id="txt" name="txt">  <button type="button" class="btn btn-primary btn-sm">Search</button>

        </center>
        <table width="100%" border="1">
            <tr>
                <th><b>NutritionId</b>&nbsp;</th>
                <th><b>Name</b>&nbsp;</th>
                <th><b>ViewNutrients</b>&nbsp;</th>

            </tr>
            
            <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td><u><a href="#">ClickHere</a></u>&nbsp;</td>

            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td><u><a href="#">ClickHere</a></u>&nbsp;</td>

            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td><u><a href="#">ClickHere</a></u>&nbsp;</td>

            </tr>

        </table>
        <br/>
        <div align="center">
            <input type="button" class="btn btn-primary btn-sm" value="ADD" onclick="location.href='@Url.Action("Add","Cookedfood")'"/>
            
            <button type="button" class="btn btn-primary btn-sm">Cancel</button>
        </div>

       
    </div>
</body>
</html>

CORF_MGMT/Views/Home/Index.cshtml
@*<h1 style="text-align:center">Welcome to CORF</h1><br />
    <h1 style="text-align:center">Nutrition Research System</h1><br/>*@
@*<a href="Login.cshtml"><center><u>Click here to Login</u></center></a>*@

<table>
    <td>
        <img src="~/image/Nutrition-at-the-heart-of-the-SDGs_001.jpg" width="350" height="350" />
    </td>
    <td>
        <h2>
            <font size="12" color="lightpink " Open Sans"">
                <center>
                    <b>
                        Welcome to CORF Nutrition Research System
                    </b>
                </center>
            </font>
        </h2>
        <center style="color:lightgreen;">@Html.ActionLink("Click here to Login", "Login", "Login")</center>
    </td>
</table>

CORF_MGMT/Views/Login/Login.cshtml
@model CORF_MGMT.user

@{
    ViewBag.Title = "Login";
}

<html>

    <head>
        @*<meta name="viewport" content="width=device-width, initial-scale=1">*@
<style>
        body {
            font-family: Arial, Helvetica, sans-serif;
        }

        form {
            border: 3px solid white;
        }

        input[type=text], input[type=password] {
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #ccc;
            box-sizing: border-box;
        }
    input[type=button] {
        width: auto;
        padding: 8px 12px;
        background-color: Highlight;
    }
        button {
            /*color: white;*/
            padding: 8px 10px;
            margin: 8px 0;
            border: none;
            cursor: pointer;
            width: 100%;
        }

            button:hover {
                opacity: 0.8;
            }

        .cancelbtn {
            width: auto;
            padding: 8px 12px;
            background-color: Highlight;
        }

        .imgcontainer {
            text-align: center;
            margin: 10px 0 12px 0;
        }

        img.avatar {
            width: 15%;
            border-radius: 15%;
        }

        /*.container {
        padding: 10px;
        width:70%;
        align:center;
    }*/

        span.psw {
            float: right;
            padding-top: 16px;
        }

        /* Change styles for span and cancel button on extra small screens */

</style>
</head>


    <body>

        @*<h2>Login Form</h2>*@
        <h1 align="center">Sign In</h1>

        <div class="imgcontainer">
            <img src="~/image/corf_logo.png" alt="Avatar" class="avatar" />
        </div>
        @using (Html.BeginForm("Login1", "Login", FormMethod.Post))
        {
        <div class="form-group" align="center">

            @*<label for="uname"><b>Username</b></label>
            <input type="text" class="form-control" placeholder="Enter Username" name="uname" required>*@
            uname @Html.TextBoxFor(l => l.Email_id)
            <br />

            @*<label for="psw"><b>Password</b></label>
            <input type="password" placeholder="Enter Password" name="psw" required>*@
            password @Html.TextBoxFor(l => l.Password)

        </div>
        <div class="form-group">
            <center>

                
                <button type="submit" class="cancelbtn">Submit</button>
                &nbsp;  &nbsp;
                <input type="button"  value="Refresh" onclick="location.href='@Url.Action("Login","Login")'"/>
                &nbsp;  &nbsp;
                <input type="button" value="Cancel"  onclick="location.href='@Url.Action("Index","Home")'" />
               
            </center>
        </div>
        }
    </body>
</html>

CORF_MGMT/Views/Shared/MenuLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@Page.Title</title>
    @RenderSection("head", required: false)
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    @RenderBody()
    <h1>Nutrition Research System-Main Menu</h1>
    <nav class="navbar navbar-inverse">
        <ul class="nav navbar-nav">
            @*<li><a href="~/">Study</a></li>*@
            <li><a href="/Study/Study" class="elements"><span>Study</span></a></li>
            <li><a href="#">Enroll Subjects</a></li>
            <li><a href="#">Nutrition Master</a></li>
            <li><a href="#">Raw Materials</a></li>
            <li><a href="#">Cooked Foods</a></li>
            <li><a href="#">Food Consumption Records</a></li>
            <li><a href="#">Research associate details</a></li>
            <li><a href="#">Report</a></li>
            <li><a href="#">Logout</a></li>
            
        </ul>
        @*<p class="navbar-text">Some text</p>*@
    </nav>

</body>


</html>

CORF_MGMT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @*<title>@ViewBag.Title - My ASP.NET Application</title>*@
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    @*<link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />*@
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>


    <div class="container body-content">
        @RenderBody()

        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - #CORF - 3Edge Solution</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

CORF_MGMT/Views/Study/Study.cshtml
@model IEnumerable<CORF_MGMT.study>

@{
    ViewBag.Title = "Study";
}

@*<h2>Study</h2>*@
<style>
    .Create {
        background-color:whitesmoke;
    }
    .sai {
        color:white
    }
</style>

<form style="background-color:black">
    <div>
        <h1 style="color:white"><center>Create/Maintain Study</h1><br />
        <table align="center" colspan="2">
            <tr>
                <td>
                    <label class="sai">SelectStudy</label>
                    <select>
                        <option value="Dropdown"></option>
                        <option value="Dropdown">Adults</option>
                        <option value="Dropdown">Child</option>
                        <option value="Dropdown">Oldpeople</option>


                    </select>
                    <br />
                    <br />

                </td>
                <div style="background-color:palevioletred">

            <tr>
                <td>

                    <input type="button" class="Create" value="Create" onClick="location.href='@Url.Action("create","Study")'" /> &nbsp;&nbsp;
                    <button class="Create" type="button">Update</button>&nbsp;&nbsp;
                    <input value="Back" class="Create" type="button" onClick="location.href='@Url.Action("Index","test")'"/>

                </td>
            </tr>


    </div>

    </tr>

    </table>

    </div>

</form>

CORF_MGMT/Views/Study/create.cshtml
@model CORF_MGMT.study

@*@{
        Layout = null;
    }

    <!DOCTYPE html>

    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>create</title>
    </head>
    <body>
        <div>
        </div>
    </body>
    </html>*@


@{
    ViewBag.Title = "create";
}


<style>
    .Create {
        background-color: aquamarine;
    }
</style>
<form>
    <div>
        <h1 align="center">Study Details</h1><br />
        <table align="center">
            <tr>
                <td>
                    <label>Study Id </label>
                </td>
                <td>
                    <input type="text" name="firstname" required>
                </td>



            </tr>
            <tr>
                <td>
                    <label>Objective </label>
                </td>
                <td>
                    <input type="text" name="firstname" required>
                </td>
            </tr>
            <tr>
                <td>
                    <label>Start Date </label>
                </td>
                <td>
                    <input type="text" name="firstname" required>
                </td>
                <td>
                    <label>End Date </label>
                </td>
                <td>
                    <input type="text" name="firstname" required>

                </td>
            </tr>
            <tr>
                <td>
                    <label>Study Duration </label>
                </td>
                <td>
                    <input type="text" name="firstname" required>
                    <label>months</label>
                </td>
            </tr>
            <tr>
                <td>
                    <label>Sample Size </label>
                </td>
                <td>
                    <input type="text" name="firstname" required>
                </td>
            </tr>
            <tr>
                <td>
                    <label>Number Of Visits </label>
                </td>
                <td>
                    <input type="text" name="firstname" required>
                </td>
            </tr>
            <tr>
                <td>
                    <label>Population type </label>
                </td>
                <td>
                    <input type="radio" name="Adults">   Adults


                    <input type="radio" name="Children">  Children
                </td>
            </tr>
            <br />
            <br />
            <div align="center">
                <tr>
                    <td></td>
                    <td>
                        <input class="Create" type="button" value="Save" onclick="location.href='@Url.Action("save","Study")'" />&nbsp;&nbsp;&nbsp;
                        <input class="Create" type="button" value=" Refresh" onclick="location.href='@Url.Action("create","Study")'" />      &nbsp;&nbsp;&nbsp;
                        <input class="Create" type="button" value="Cancel" onclick="location.href='@Url.Action("Study","Study")'" />
                    </td>
                </tr>
            </div>
        </table>
    </div>
</form>